[[plugins]]
repo = 'dracula/vim'
hook_add = '''
  let g:dracula_colorterm = 0
  colorscheme dracula
'''

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = '''
" Grep:
call denite#custom#var('grep', 'command', ['ag'])
call denite#custom#var('grep', 'default_opts',
      \\ ['-i', '--vimgrep'])
call denite#custom#var('grep', 'recursive_opts', [])
call denite#custom#var('grep', 'pattern_opt', [])
call denite#custom#var('grep', 'separator', ['--'])
call denite#custom#var('grep', 'final_opts', [])
let s:ignore_globs = ['.git', '.svn', 'node_modules', 'log', 'logs']
call denite#custom#var('file/rec', 'command', [
      \\ 'ag',
      \\ '--follow',
      \\ ] + map(deepcopy(s:ignore_globs), { k, v -> '--ignore=' . v }) + [
      \\ '--nocolor',
      \\ '--nogroup',
      \\ '-g',
      \\ ''
      \\ ])
call denite#custom#source('file/rec', 'matchers', ['matcher/substring'])
call denite#custom#filter('matcher/ignore_globs', 'ignore_globs', s:ignore_globs)

" Denite:
nnoremap <silent> ;f :<C-u>Denite file/rec -split=floating -winrow=1<CR>
nnoremap <silent> ;s :<C-u>Denite -buffer-name=search grep -split=floating -winrow=1<CR>

autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \\ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \\ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \\ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \\ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \\ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \\ denite#do_map('toggle_select').'j'
endfunction
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'thinca/vim-qfreplace'
