[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'terryma/vim-multiple-cursors'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'thinca/vim-qfreplace'

